Refactoring.
 * Added `panic` function that yells and exits.
 * Minor improvements (less polluted console output etc).

Change-Id: eef659d552
Story-Id: 78913658

diff --git a/gitflow2/git-flow2-feature-start b/gitflow2/git-flow2-feature-start
--- a/gitflow2/git-flow2-feature-start
+++ b/gitflow2/git-flow2-feature-start
@@ -10,6 +10,7 @@ set -o pipefail;
 . git-flow2-rainbow.sh
 . git-flow2-spinner.sh
 . git-flow2-common.sh
+. git-flow2-pivotal.sh
 
 ensure_repo_is_initialized
 
@@ -47,63 +48,30 @@ function rollback_branch {
   [[ -n "${new_branch}" ]] && git branch -D ${new_branch}
 }
 
-function set_me_as_pt_story_owner {
+
+function update_pt_story {
   local story_id=$1
-  local new_branch=$2
+  local branch_to_rollback=$2
+
+  start_spinner "Setting story #${story_id} state to 'started'"
+  __out=$(pt_start_story "${PROJECT_ID}" "${story_id}") || {
+    [[ -n "${branch_to_rollback}" ]] && rollback_branch ${branch_to_rollback}
+    panic "Pivotal Tracker reported an error." "${__out}"
+  }
+  stop_spinner 0
 
   start_spinner "Setting you as the owner of story ${story_id}..."
-  pt_user_id=$(curl -s -X GET -H "X-TrackerToken: ${PIVOTAL_TOKEN}" "https://www.pivotaltracker.com/services/v5/me" 2>/dev/null | \
-    underscore extract id)
-
-  if [[ -z "${pt_user_id}" ]]; then
-    print_scream
-    echo "${__bold}Oops... Could not determine your Pivotal Tracker user id.${__normal}"
-    rollback_branch ${new_branch}
-    exit 1
-  fi
-
-  # Set the story owner field to me.
-  # PT reports errors in JSON output with HTTP 200 so we have to parse what we get.
-  __out=$(curl -X PUT -H "X-TrackerToken: ${PIVOTAL_TOKEN}" \
-    -H "Content-Type: application/json" \
-    -d "{\"owner_ids\": [${pt_user_id}]}" \
-    --silent \
-    "https://www.pivotaltracker.com/services/v5/projects/${PROJECT_ID}/stories/${story_id}") || {
-    echo "Something went wront when trying to access Pivotal Tracker server."
-    rollback_branch ${new_branch}
-    exit 1
-  }
-  stop_spinner 0
-
-  # Check if there were errors.
-  pt_error=$(echo ${__out} | underscore select ".error" --outfmt text)
-  if [[ -n "${pt_error}" ]]; then
-    echo 
-    echo "${__bold}Oops, I could not set the story owner to you.${__normal}"
-    print_scream
-    echo "Please set yourself as the owner of in the web UI using the following link:"
-    echo "https://www.pivotaltracker.com/n/projects/${PROJECT_ID}/stories/${story_id}" 
-    echo
-    echo "original error: ${pt_error}"
-  fi
-}
-
-function start_story {
-  local story_id=$1
-
-  # Instruct PT backend to update the story.
-  start_spinner "Setting story #${story_id} state to 'started'"
-  echo
-  __out=$(pivotal_tools start story ${story_id} --project-id ${PROJECT_ID}) || {
-    echo
-    echo "${__bold}Pivotal Tracker reported an error.${__normal}"
-    print_scream
-    echo "${__bold}${__out}${__normal}"
-    exit 1
+  __out=$(pt_set_me_as_story_owner "${PROJECT_ID}" "${story_id}") || {
+    [[ -n "${branch_to_rollback}" ]] && rollback_branch ${branch_to_rollback}
+      echo
+      echo "${__bold}Oops, I could not set the story owner to you.${__normal}"
+      echo "Please set yourself as the owner of in the web UI using the following link:"
+      echo "https://www.pivotaltracker.com/n/projects/${PROJECT_ID}/stories/${story_id}"
+      echo
+      [[ -n "${DEBUG}" ]] && echo "original error: ${__out}"
   }
   stop_spinner 0
 }
-
 
 
 # Deal with Pivotal Tracker
@@ -241,9 +209,7 @@ git checkout -b ${new_branch}
 
 echo
 echogreen "Enter Pivotal Tracker"
-
-start_story "${story_id}"
-set_me_as_pt_story_owner "${story_id}" "${new_branch}"
+update_pt_story ${story_id} ${new_branch}
 
 # Aaaaand we're good!
 echo
diff --git a/gitflow2/git-flow2-review-update b/gitflow2/git-flow2-review-update
--- a/gitflow2/git-flow2-review-update
+++ b/gitflow2/git-flow2-review-update
@@ -23,12 +23,11 @@ function cleanup {
   stop_spinner 0
 }
 
-# Mae sure user has `underscore-cli` installed.
+# Make sure user has `underscore-cli` installed.
 _=$(underscore --version 2>/dev/null) || {
-  print_scream
-  echo "${__bold}Looks like you don't have underscore-cli installed!${__normal}"
-  echo "Run 'npm install -g underscore-cli' like, right now!"
-  exit 1
+  panic \
+    "Looks like you don't have underscore-cli installed!" \
+    "Run 'npm install -g underscore-cli' like, right now!"
 }
 
 
@@ -38,14 +37,16 @@ STORY_ID_RX="s|.*\([0-9]\{8,9\}\).*|\1|"
 
 function handle_missing_story_id {
   last_commit_sha=$(git log -1 --pretty=format:"%h")
-  echo "${__bold}Oh noes, I could not update your review!${__normal}"
-  print_scream
-  echo "${__bold}Story id not found in commit message for '${last_commit_sha}'${__normal}."
-  echo
-  echo "Please use 'git commit --amend' to add a 'story-id: <PT story id>' line."
-  echo "That's what I use to figure out what story your commit relates to and I can "
-  echo "find the relevant review to update."
-  exit 1
+  function __msg {
+    echo "${__bold}Story id not found in commit message for '${last_commit_sha}'${__normal}."
+    echo
+    echo "Please use 'git commit --amend' to add a 'story-id: <PT story id>' line."
+    echo "That's what I use to figure out what story your commit relates to and I can "
+    echo "find the relevant review to update."
+  }
+  panic \
+    "Oh noes, I could not update your review!" \
+    __msg
 }
 
 
@@ -116,13 +117,11 @@ start_spinner "Loading ReviewBoard repositories..."
 # We need to limit number review request update candidates. So we want to know the
 # RB repo id. This is how we find it.
 rb_repo_id=$(rbt api-get /repositories --max-results=200 | \
-  underscore extract 'repositories' | \
-  underscore find "value.path.indexOf('${github_repo}') >= 0" | \
-  underscore extract 'id' --outfmt text) || {
-
+    underscore extract 'repositories' 2>/dev/null | \
+    underscore find "value.path.indexOf('${github_repo}') >= 0" | \
+    underscore extract 'id' --outfmt text 2>/dev/null) || {
   echo
-  echo "Failed to load ReviewBoard repositories..."
-  exit 1
+  panic "Failed to load ReviewBoard repositories..."
 }
 stop_spinner 0
 
