Make sure gitflow config file or branch is not mentioned anywhere.
Abstract out the names.

Change-Id: b35364c3cd
Story-Id: 78913658

diff --git a/gitflow2/git-flow2-init b/gitflow2/git-flow2-init
--- a/gitflow2/git-flow2-init
+++ b/gitflow2/git-flow2-init
@@ -66,10 +66,10 @@ echo -n "Sweet, all the required branches exist! "; print_checkmark;
 echo
 echored "Local Config"
 
-if ! git show develop:salsaflow.yml 2>/dev/null >/dev/null; then
+if ! git show develop:${CONFIG_FILE} 2>/dev/null >/dev/null; then
   mark_action_required
   echo "Please make sure there's a 'pivotal_tracker' section with "
-  echo "'project_id: <PT PROJECT ID>' in 'salsaflow.yml' file in branch 'develop'"
+  echo "'project_id: <PT PROJECT ID>' in '${CONFIG_FILE}' file in branch 'develop'"
   echo "Example setting:"
   echo
   echo -e "  pivotal_tracker:\n    project_id: MY_PT_PROJECT_ID"
@@ -80,9 +80,9 @@ fi
 echo
 echored "Global Config"
 
-if [[ ! -f "${HOME}/.salsaflow.yml" ]]; then
+if [[ ! -f "${CONFIG_FILE_GLOBAL}" ]]; then
   mark_action_required
-  echo "I can't find the file '${HOME}/.salsaflow.yml'."
+  echo "I can't find the file '${CONFIG_FILE_GLOBAL}'."
   echo "No hard feelings but I need it. So please create it."
   echo "And make sure there's a 'pivotal_tracker' section with 'token' property "
   echo "that has your Pivotal Tracker API token as the value."
